# Database connection username and password
spring:
  datasource:
    url: jdbc:mysql://beer.cdahouwwyloj.us-east-2.rds.amazonaws.com:3306/beer
    username: admin
    password: SenhaSenha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 9000
  context-path: /beerhouse
